list_of_collabs = [
    'Yann Dubois',
    'Daksh Idnani',
    'Kevin Murphy',
    'Devi Parikh',
    'Samy Bengio',
    'Dhruv Batra',
    'Larry Zitnick',
    'Xiao Lin',
    'Tanmay Batra',
    'Satwik Kottur',
    'Jose Moura',
    'Gal Chechik',
    'Prithvijit Chattophadhyay',
    'Ramprasaath R. Selvaraju',
    'Ashwin K Vijayakumar',
    'Michael Cogswell',
    'Abhishek Das',
    'Ian Fischer',
    'Jonathan Huang',
    'Karan Desai',
    'Stefan Lee', 
    'Marcus Rohrbach',
    'Nirbhay Modhe',
    'Mohit Sharma',
    'Douwe Kiela',
    'David J. Schwab',
    'Arthur Szlam',
    'Maximilian Nickel',
    'Ari Morcos',
    'Brenden Lake',
    'David Lopez-Paz',
    'Sirui Xie',
    'Song-Chun Zhu',
    'Daksh Idnani',
    'Vivek Madan',
    'Naman Goyal',
    'Corentin Dancette',
    'Spencer Whitehead',
    'Rishabh Maheshwary',
    'Stefan Scherer',
    'Xinlei Chen',
    'Matthieu Cord',
    'Tanmay Rajpurohit',
    'Justin Johnson',
    'Polina Kirichenko',
    'Mark Ibrahim',
    'Randall Balestriero',
    'Diane Bouchacourt',
    'Hamed Firooz',
    'Andrew Gordon Wilson',
    'Yunzhen Feng',
    'Julia Kempe',
    'Piotr Dollar',
    'Saurabh Gupta',
    'Tsung-Yi Lin',
    'Hao Fang',
]

import random
random.shuffle(list_of_collabs)

for x in list_of_collabs:
    print(x)